{% set name = "miniQuant" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/Tidesun/Mini/archive/refs/tags/{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "wget -qO- https://miniquant.s3.us-east-2.amazonaws.com/pretrained_models.tar.gz | tar xvz | {{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python ==3.9.7
  run:
    - python ==3.9.7
    - Cython==0.29.22
    - dill==0.3.3
    - intervaltree==3.1.0
    - numpy==1.17.2
    - pandas==1.1.5
    - Pillow==8.2.0
    - psutil==5.8.0
    - pyparsing==2.4.7
    - pysam==0.21.0
    - python-dateutil==2.8.1
    - pytz==2021.1
    - scipy==1.5.4
    - scs==2.1.4
    - six==1.16.0
    - sortedcontainers==2.3.0
    - typing-extensions==3.10.0.0
    - xgboost==2.0.3
    - scikit-learn==1.0.2

about:
  home: "https://github.com/Augroup/miniQuant"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for interactive mapping"
  doc_url: https://geodemo.gishub.org
  dev_url: https://github.com/giswqs/geodemo